name: build devel branch
on:
  push:
    tags:
      - dev-*
jobs:
  build-devel:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - run: cmd.exe /c build\buildall.bat Release GA
      - run: dir; dir bin; dir bin\Release
      - run: Compress-Archive "bin\Release\*" "bin\Poderosa-snapshot-${{ github.ref_name }}.zip"
      - run: dir bin
      - uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build/*.log
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          artifacts: bin/*.zip
